const items = [
  {title: 'Men - Brown Regular Fit Crew-Neck T-Shirt - Size: XXL - H&M',
   category: 'Womens Clothing - Joggers',
   stars: '*****',
   image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
   price: '$176',
   sale: '$84'
  },
  {title: 'A-Lab Trip on This Black T-Shirt - Size: L',
  category: 'Mens Clothing - T-Shirts',
  stars: '***',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$34',
  sale: '$16'
  },
  {title: 'Mens Hennything Is Possible Short Sleeve Crew Tee Shirt',
  category: 'Childrens Clothing - Jumpers',
  stars: '****',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$130',
  sale: '$76'
  },
  {title: 'Men - Brown Regular Fit Crew-Neck T-Shirt - Size: XXL - H&M',
   category: 'Womens Clothing - Joggers',
   stars: '*****',
   image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
   price: '$176',
   sale: '$84'
  },
  {title: 'A-Lab Trip on This Black T-Shirt - Size: L',
  category: 'Mens Clothing - T-Shirts',
  stars: '***',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$34',
  sale: '$16'
  },
  {title: 'Mens Hennything Is Possible Short Sleeve Crew Tee Shirt',
  category: 'Childrens Clothing - Jumpers',
  stars: '****',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$130',
  sale: '$76'
  },
  {title: 'Men - Brown Regular Fit Crew-Neck T-Shirt - Size: XXL - H&M',
   category: 'Womens Clothing - Joggers',
   stars: '*****',
   image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
   price: '$176',
   sale: '$84'
  },
  {title: 'A-Lab Trip on This Black T-Shirt - Size: L',
  category: 'Mens Clothing - T-Shirts',
  stars: '***',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$34',
  sale: '$16'
  },
  {title: 'Mens Hennything Is Possible Short Sleeve Crew Tee Shirt',
  category: 'Childrens Clothing - Jumpers',
  stars: '****',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$130',
  sale: '$76'
  },
  {title: 'Men - Brown Regular Fit Crew-Neck T-Shirt - Size: XXL - H&M',
   category: 'Womens Clothing - Joggers',
   stars: '*****',
   image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
   price: '$176',
   sale: '$84'
  },
  {title: 'A-Lab Trip on This Black T-Shirt - Size: L',
  category: 'Mens Clothing - T-Shirts',
  stars: '***',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$34',
  sale: '$16'
  },
  {title: 'Mens Hennything Is Possible Short Sleeve Crew Tee Shirt',
  category: 'Childrens Clothing - Jumpers',
  stars: '****',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$130',
  sale: '$76'
  },
  {title: 'Men - Brown Regular Fit Crew-Neck T-Shirt - Size: XXL - H&M',
   category: 'Womens Clothing - Joggers',
   stars: '*****',
   image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
   price: '$176',
   sale: '$84'
  },
  {title: 'A-Lab Trip on This Black T-Shirt - Size: L',
  category: 'Mens Clothing - T-Shirts',
  stars: '***',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$34',
  sale: '$16'
  },
  {title: 'Mens Hennything Is Possible Short Sleeve Crew Tee Shirt',
  category: 'Childrens Clothing - Jumpers',
  stars: '****',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$130',
  sale: '$76'
  },
  {title: 'Men - Brown Regular Fit Crew-Neck T-Shirt - Size: XXL - H&M',
   category: 'Womens Clothing - Joggers',
   stars: '*****',
   image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
   price: '$176',
   sale: '$84'
  },
  {title: 'A-Lab Trip on This Black T-Shirt - Size: L',
  category: 'Mens Clothing - T-Shirts',
  stars: '***',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$34',
  sale: '$16'
  },
  {title: 'Mens Hennything Is Possible Short Sleeve Crew Tee Shirt',
  category: 'Childrens Clothing - Jumpers',
  stars: '****',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$130',
  sale: '$76'
  },
  {title: 'Men - Brown Regular Fit Crew-Neck T-Shirt - Size: XXL - H&M',
   category: 'Womens Clothing - Joggers',
   stars: '*****',
   image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
   price: '$176',
   sale: '$84'
  },
  {title: 'A-Lab Trip on This Black T-Shirt - Size: L',
  category: 'Mens Clothing - T-Shirts',
  stars: '***',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$34',
  sale: '$16'
  },
  {title: 'Mens Hennything Is Possible Short Sleeve Crew Tee Shirt',
  category: 'Childrens Clothing - Jumpers',
  stars: '****',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$130',
  sale: '$76'
  },
  {title: 'Men - Brown Regular Fit Crew-Neck T-Shirt - Size: XXL - H&M',
   category: 'Womens Clothing - Joggers',
   stars: '*****',
   image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
   price: '$176',
   sale: '$84'
  },
  {title: 'A-Lab Trip on This Black T-Shirt - Size: L',
  category: 'Mens Clothing - T-Shirts',
  stars: '***',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$34',
  sale: '$16'
  },
  {title: 'Mens Hennything Is Possible Short Sleeve Crew Tee Shirt',
  category: 'Childrens Clothing - Jumpers',
  stars: '****',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$130',
  sale: '$76'
  }
];

export default items;