const items = [
  {title: 'Men - Brown Regular Fit Crew-Neck T-Shirt - Size: XXL - H&M',
   category: 'Womens Clothing - Joggers',
   stars: '*****',
   image: 'https://particle.scitech.org.au/app/uploads/2021/10/shutterstock_274092959.jpg',
   price: '$176',
   sale: '$84'
  },
  {title: 'A-Lab Trip on This Black T-Shirt - Size: L',
  category: 'Mens Clothing - T-Shirts',
  stars: '***',
  image: 'https://cdn.shopify.com/s/files/1/0137/6210/1348/collections/112991633508_2000x.jpg?v=1629297835',
  price: '$34',
  sale: '$16'
  },
  {title: 'Mens Hennything Is Possible Short Sleeve Crew Tee Shirt',
  category: 'Childrens Clothing - Jumpers',
  stars: '****',
  image: 'https://www.theparisreview.org/blog/wp-content/uploads/2020/01/turtle.jpg',
  price: '$130',
  sale: '$76'
  },
  {title: 'Men - Brown Regular Fit Crew-Neck T-Shirt - Size: XXL - H&M',
   category: 'Womens Clothing - Joggers',
   stars: '*****',
   image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
   price: '$176',
   sale: '$84'
  },
  {title: 'A-Lab Trip on This Black T-Shirt - Size: L',
  category: 'Mens Clothing - T-Shirts',
  stars: '***',
  image: 'https://images.thefishsite.com/fish%2Farticles%2FRASs%2Foctopus-larva-good-quality.jpg?scale.option=fill&scale.width=1200&scale.height=630&crop.width=1200&crop.height=630&crop.y=center&crop.x=center',
  price: '$34',
  sale: '$16'
  },
  {title: 'Mens Hennything Is Possible Short Sleeve Crew Tee Shirt',
  category: 'Childrens Clothing - Jumpers',
  stars: '****',
  image: 'https://www.cnet.com/a/img/resize/bf9d9130c8ee396fe33604bdf0f9daec7ea0e05a/2015/06/18/5a4d119a-f29c-42ea-97e1-1d99f3e0fe9f/cuteocky.jpg?auto=webp&width=940',
  price: '$130',
  sale: '$76'
  },
  {title: 'Men - Brown Regular Fit Crew-Neck T-Shirt - Size: XXL - H&M',
   category: 'Womens Clothing - Joggers',
   stars: '*****',
   image: 'https://img.thedailybeast.com/image/upload/c_crop,d_placeholder_euli9k,h_1439,w_2560,x_0,y_0/dpr_1.5/c_limit,w_1044/fl_lossy,q_auto/v1492181040/articles/2015/05/22/does-the-octopus-have-a-soul/150521-oconnor-octopus-tease_zenfje',
   price: '$176',
   sale: '$84'
  },
  {title: 'A-Lab Trip on This Black T-Shirt - Size: L',
  category: 'Mens Clothing - T-Shirts',
  stars: '***',
  image: 'https://files.worldwildlife.org/wwfcmsprod/images/Shark_Whitetip_GPN257599_Species/story_full_width/7u6ythcedl_GPN257599_whitetip_shark.jpg',
  price: '$34',
  sale: '$16'
  },
  {title: 'Mens Hennything Is Possible Short Sleeve Crew Tee Shirt',
  category: 'Childrens Clothing - Jumpers',
  stars: '****',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$130',
  sale: '$76'
  },
  {title: 'Men - Brown Regular Fit Crew-Neck T-Shirt - Size: XXL - H&M',
   category: 'Womens Clothing - Joggers',
   stars: '*****',
   image: 'https://images.squarespace-cdn.com/content/v1/5486159de4b074841b303621/1625098587656-RAWMEEYLSLFFNK7J2F5O/WEBimage1.jpg',
   price: '$176',
   sale: '$84'
  },
  {title: 'A-Lab Trip on This Black T-Shirt - Size: L',
  category: 'Mens Clothing - T-Shirts',
  stars: '***',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$34',
  sale: '$16'
  },
  {title: 'Mens Hennything Is Possible Short Sleeve Crew Tee Shirt',
  category: 'Childrens Clothing - Jumpers',
  stars: '****',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$130',
  sale: '$76'
  },
  {title: 'Men - Brown Regular Fit Crew-Neck T-Shirt - Size: XXL - H&M',
   category: 'Womens Clothing - Joggers',
   stars: '*****',
   image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
   price: '$176',
   sale: '$84'
  },
  {title: 'A-Lab Trip on This Black T-Shirt - Size: L',
  category: 'Mens Clothing - T-Shirts',
  stars: '***',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$34',
  sale: '$16'
  },
  {title: 'Mens Hennything Is Possible Short Sleeve Crew Tee Shirt',
  category: 'Childrens Clothing - Jumpers',
  stars: '****',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$130',
  sale: '$76'
  },
  {title: 'Men - Brown Regular Fit Crew-Neck T-Shirt - Size: XXL - H&M',
   category: 'Womens Clothing - Joggers',
   stars: '*****',
   image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
   price: '$176',
   sale: '$84'
  },
  {title: 'A-Lab Trip on This Black T-Shirt - Size: L',
  category: 'Mens Clothing - T-Shirts',
  stars: '***',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$34',
  sale: '$16'
  },
  {title: 'Mens Hennything Is Possible Short Sleeve Crew Tee Shirt',
  category: 'Childrens Clothing - Jumpers',
  stars: '****',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$130',
  sale: '$76'
  },
  {title: 'Men - Brown Regular Fit Crew-Neck T-Shirt - Size: XXL - H&M',
   category: 'Womens Clothing - Joggers',
   stars: '*****',
   image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
   price: '$176',
   sale: '$84'
  },
  {title: 'A-Lab Trip on This Black T-Shirt - Size: L',
  category: 'Mens Clothing - T-Shirts',
  stars: '***',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$34',
  sale: '$16'
  },
  {title: 'Mens Hennything Is Possible Short Sleeve Crew Tee Shirt',
  category: 'Childrens Clothing - Jumpers',
  stars: '****',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$130',
  sale: '$76'
  },
  {title: 'Men - Brown Regular Fit Crew-Neck T-Shirt - Size: XXL - H&M',
   category: 'Womens Clothing - Joggers',
   stars: '*****',
   image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
   price: '$176',
   sale: '$84'
  },
  {title: 'A-Lab Trip on This Black T-Shirt - Size: L',
  category: 'Mens Clothing - T-Shirts',
  stars: '***',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$34',
  sale: '$16'
  },
  {title: 'Mens Hennything Is Possible Short Sleeve Crew Tee Shirt',
  category: 'Childrens Clothing - Jumpers',
  stars: '****',
  image: 'https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350',
  price: '$130',
  sale: '$76'
  }
];

export default items;